version: '3'

services:
  itemsbasket.basketservice:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    ports:
      - "80"
  itemsbasket.itemsservice:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    ports:
      - "80"
  itemsbasket.ui:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    ports:
      - "80"
networks:
  default:
    external:
      name: nat


